name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - "27017:27017"
        options: --health-cmd "mongo --eval 'db.stats().ok'" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      # Checkout the repository to the runner
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          docker-compose -f docker-compose.yml up -d

      # Build and Test Server
      - name: Build and Test Server
        run: |
          cd server
          npm install -g nodemon
          npm install

      # Build Client
      - name: Build Client
        run: |
          cd client
          npm config set legacy-peer-deps true
          npm install
          npm run build

      # Stop Docker Compose services
      - name: Stop Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
